/* ==========================================================================
   LEHA NEPLOXO — i18n dictionary + placeholder project data
   Edit this file to add real projects/texts later. Nothing here is invented
   biography/achievements — only structural placeholders per the brief.
   ========================================================================== */

window.SITE_I18N = {
  ua: {
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.services": "SERVICES",
    "nav.projects": "PROJECTS",
    "nav.socials": "SOCIALS",
    "nav.support": "SUPPORT",
    "lang.label": "Мова",

    "hero.kicker": "Personal creator",
    "hero.subtitle": "Digital projects / Content",
    "hero.cta.primary": "MY PROJECTS",
    "hero.cta.secondary": "Підтримати автора",
    "hero.scroll": "Scroll",

    "about.label": "ABOUT",
    "about.title": "Хто такий Леха Неплохо",
    "about.intro": "Леха Неплохо (LEHA NEPLOXO) — автор, контент-мейкер і людина за кадром. Займаюся розробкою — створюю сайти, програми та боти під задачі бізнесу і людей.",
    "about.note": "Послуги розробки ↓",
    "hero.alt": "Портрет Лехи Неплохо (LEHA NEPLOXO)",
    "about.alt": "Фото Лехи Неплохо (LEHA NEPLOXO)",

    "services.label": "SERVICES",
    "services.title": "Розробка на замовлення",
    "services.card1.title": "Сайти",
    "services.card1.desc": "Лендинги та сайти під ключ — від дизайну до запуску.",
    "services.card2.title": "Програми",
    "services.card2.desc": "Автоматизація та інструменти: десктоп- і веб-рішення під задачу.",
    "services.card3.title": "Боти",
    "services.card3.desc": "Telegram/Discord-боти, міні-ігри та автоматизація процесів.",
    "services.card4.title": "ШІ-рішення",
    "services.card4.desc": "Інтеграція нейромереж, автоматизація та ШІ-інструменти під ваші задачі.",
    "services.cta": "Замовити проєкт",

    "showcase.label": "SHOWCASE",
    "showcase.title": "У русі, у кадрі",
    "showcase.sub": "Відео як частина історії, а не просто фон.",
    "showcase.cta": "Дивитись у повному екрані",

    "projects.label": "PORTFOLIO",
    "projects.title": "MY PROJECTS",
    "projects.sub": "Портфоліо завершених і поточних проєктів.",
    "projects.card.category": "Скоро",
    "projects.card.date": "TBA",
    "projects.card.desc": "Опис проєкту буде додано найближчим часом.",
    "projects.card.cta": "VIEW PROJECT",

    "socials.label": "FOLLOW ME",
    "socials.title": "Соціальні мережі",
    "socials.sub": "Офіційні акаунти LEHA NEPLOXO.",

    "ads.label": "ADVERTISING",
    "ads.title": "Реклама та колаборації",
    "ads.text": "Розміщую рекламні інтеграції в TikTok, Instagram, YouTube та Facebook — під формат і аудиторію кожної площадки.",
    "ads.cta": "Замовити рекламу",

    "support.label": "SUPPORT",
    "support.title": "Підтримка проєкту",
    "support.text": "Якщо контент відгукується — підтримка допомагає створювати більше.",
    "support.cta": "Підтримати автора",
    "support.via": "через Monobank",

    "footer.tagline": "Personal creator / Digital projects / Content",
    "footer.nav": "Навігація",
    "footer.social": "Соцмережі",
    "footer.lang": "Мова",
    "footer.rights": "Усі права захищені.",

    "project.back": "НАЗАД ДО ПРОЄКТІВ",
    "project.about": "Про проєкт",
    "project.gallery": "Матеріали",
    "project.links": "Посилання",
    "project.notfound.title": "Проєкт не знайдено",
    "project.notfound.text": "Такого проєкту ще не існує. Поверніться до списку проєктів.",
    "project.notfound.cta": "ДО ПРОЄКТІВ",
    "project.placeholder": "Повний опис, матеріали та посилання цього проєкту з’являться найближчим часом.",

    "projects.cyber.title": "CYBER BIOLOGY",
    "projects.cyber.category": "Digital evolution",
    "projects.cyber.desc": "Світи, де прості боти народжуються, борються за енергію та еволюціонують.",
    "projects.cyber.desc.long": "Серія експериментів зі штучною еволюцією: у кожному світі власні правила народження, голоду, розмноження та мутацій. Боти рухаються, шукають їжу і борються за виживання — без жодного сценарію, лише випадковість і код.",
    "project.worlds.label": "EXPERIMENTS",
    "project.worlds.title": "Світи ботів",
    "project.worlds.sub": "Кожен світ — окрема жива симуляція. Відкривайте та спостерігайте.",
    "project.world.enter": "УВІЙТИ У СВІТ",
    "project.world.number": "Світ ботів",
    "world.back": "НАЗАД ДО ПРОЄКТУ",

    "projects.tiktokgame.title": "STREET FIGHTERS",
    "projects.tiktokgame.category": "Прямий ефір",
    "projects.tiktokgame.date": "Наразі в ефірі",
    "projects.tiktokgame.desc": "Інтерактивна гра в прямому ефірі TikTok, де ти керуєш своїм персонажем і прокачуєш його рівень.",
    "projects.tiktokgame.desc.long": "Інтерактивна гра в прямому ефірі TikTok, де ти керуєш своїм персонажем і прокачуєш його рівень.",
    "projects.tiktokgame.cta": "ДИВИТИСЬ ЕФІР",

    "projects.lehagame.title": "LEHA NEPLOXO WORLD",
    "projects.lehagame.category": "Онлайн RP · Відкритий світ",
    "projects.lehagame.date": "Грай онлайн",
    "projects.lehagame.desc": "Ціле місто у твоєму браузері: пальми, неон, океан і живі гравці. Ставай копом, медиком, пожежником чи бізнесменом, а далі вирішуй сам, ким стати.",
    "projects.lehagame.desc.long": "Ласкаво просимо до LEHA NEPLOXO WORLD — сонячного неонового мегаполіса біля океану з повністю відкритим світом. Кожен, кого ти зустрічаєш на вулицях, — реальний гравець. Купуй квартири й будинки, заробляй і будуй свій статок. Вступай на службу в поліцію, рятуй життя у швидкій допомозі або гаси пожежі разом із командою. Ганяй набережною, відпочивай на пляжі, заводь друзів чи ворогів. Ким станеш ти — вирішувати тільки тобі. Грай прямо в браузері, нічого не завантажуючи.",
    "projects.lehagame.cta": "ГРАТИ",

    "meta.introTag": "Cinematic personal brand",
    "meta.description": "Офіційний сайт Лехи Неплохо (Льоха Неплохо, LEHA NEPLOXO): блогер і розробник. Сайти, програми, боти та ШІ-рішення на замовлення, онлайн-гра LEHA NEPLOXO WORLD і соцмережі.",
    "meta.title": "Леха Неплохо (LEHA NEPLOXO) — блогер, розробник сайтів та ігор"
  },

  ru: {
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.services": "SERVICES",
    "nav.projects": "PROJECTS",
    "nav.socials": "SOCIALS",
    "nav.support": "SUPPORT",
    "lang.label": "Язык",

    "hero.kicker": "Personal creator",
    "hero.subtitle": "Digital projects / Content",
    "hero.cta.primary": "MY PROJECTS",
    "hero.cta.secondary": "Поддержать автора",
    "hero.scroll": "Scroll",

    "about.label": "ABOUT",
    "about.title": "Кто такой Леха Неплохо",
    "about.intro": "Леха Неплохо (LEHA NEPLOXO) — автор, контент-мейкер и человек за кадром. Занимаюсь разработкой — создаю сайты, программы и ботов под задачи бизнеса и людей.",
    "about.note": "Услуги разработки ↓",
    "hero.alt": "Портрет Лехи Неплохо (LEHA NEPLOXO)",
    "about.alt": "Фото Лехи Неплохо (LEHA NEPLOXO)",

    "services.label": "SERVICES",
    "services.title": "Разработка на заказ",
    "services.card1.title": "Сайты",
    "services.card1.desc": "Лендинги и сайты под ключ — от дизайна до запуска.",
    "services.card2.title": "Программы",
    "services.card2.desc": "Автоматизация и инструменты: десктоп- и веб-решения под задачу.",
    "services.card3.title": "Боты",
    "services.card3.desc": "Telegram/Discord-боты, мини-игры и автоматизация процессов.",
    "services.card4.title": "ИИ-решения",
    "services.card4.desc": "Интеграция нейросетей, автоматизация и ИИ-инструменты под ваши задачи.",
    "services.cta": "Заказать проект",

    "showcase.label": "SHOWCASE",
    "showcase.title": "В движении, в кадре",
    "showcase.sub": "Видео как часть истории, а не просто фон.",
    "showcase.cta": "Смотреть в полном экране",

    "projects.label": "PORTFOLIO",
    "projects.title": "MY PROJECTS",
    "projects.sub": "Портфолио завершённых и текущих проектов.",
    "projects.card.category": "Скоро",
    "projects.card.date": "TBA",
    "projects.card.desc": "Описание проекта будет добавлено в ближайшее время.",
    "projects.card.cta": "VIEW PROJECT",

    "socials.label": "FOLLOW ME",
    "socials.title": "Социальные сети",
    "socials.sub": "Официальные аккаунты LEHA NEPLOXO.",

    "ads.label": "ADVERTISING",
    "ads.title": "Реклама и коллаборации",
    "ads.text": "Размещаю рекламные интеграции в TikTok, Instagram, YouTube и Facebook — под формат и аудиторию каждой площадки.",
    "ads.cta": "Заказать рекламу",

    "support.label": "SUPPORT",
    "support.title": "Поддержка проекта",
    "support.text": "Если контент откликается — поддержка помогает создавать больше.",
    "support.cta": "Поддержать автора",
    "support.via": "через Monobank",

    "footer.tagline": "Personal creator / Digital projects / Content",
    "footer.nav": "Навигация",
    "footer.social": "Соцсети",
    "footer.lang": "Язык",
    "footer.rights": "Все права защищены.",

    "project.back": "НАЗАД К ПРОЕКТАМ",
    "project.about": "О проекте",
    "project.gallery": "Материалы",
    "project.links": "Ссылки",
    "project.notfound.title": "Проект не найден",
    "project.notfound.text": "Такого проекта пока не существует. Вернитесь к списку проектов.",
    "project.notfound.cta": "К ПРОЕКТАМ",
    "project.placeholder": "Полное описание, материалы и ссылки этого проекта появятся в ближайшее время.",

    "projects.cyber.title": "CYBER BIOLOGY",
    "projects.cyber.category": "Digital evolution",
    "projects.cyber.desc": "Миры, где простые боты рождаются, борются за энергию и эволюционируют.",
    "projects.cyber.desc.long": "Серия экспериментов с искусственной эволюцией: в каждом мире свои правила рождения, голода, размножения и мутаций. Боты двигаются, ищут еду и борются за выживание — без сценария, только случайность и код.",
    "project.worlds.label": "EXPERIMENTS",
    "project.worlds.title": "Миры ботов",
    "project.worlds.sub": "Каждый мир — отдельная живая симуляция. Открывайте и наблюдайте.",
    "project.world.enter": "ВОЙТИ В МИР",
    "project.world.number": "Мир ботов",
    "world.back": "НАЗАД К ПРОЕКТУ",

    "projects.tiktokgame.title": "STREET FIGHTERS",
    "projects.tiktokgame.category": "Прямой эфир",
    "projects.tiktokgame.date": "Сейчас в эфире",
    "projects.tiktokgame.desc": "Интерактивная игра в прямом эфире TikTok, где ты управляешь своим персонажем и прокачиваешь его уровень.",
    "projects.tiktokgame.desc.long": "Интерактивная игра в прямом эфире TikTok, где ты управляешь своим персонажем и прокачиваешь его уровень.",
    "projects.tiktokgame.cta": "СМОТРЕТЬ ЭФИР",

    "projects.lehagame.title": "LEHA NEPLOXO WORLD",
    "projects.lehagame.category": "Онлайн RP · Открытый мир",
    "projects.lehagame.date": "Играй онлайн",
    "projects.lehagame.desc": "Целый город в твоём браузере: пальмы, неон, океан и живые игроки. Становись копом, медиком, пожарным или бизнесменом, а дальше решай сам, кем стать.",
    "projects.lehagame.desc.long": "Добро пожаловать в LEHA NEPLOXO WORLD — солнечный неоновый мегаполис у океана с полностью открытым миром. Каждый, кого ты встречаешь на улицах, — реальный игрок. Покупай квартиры и дома, зарабатывай и строй своё состояние. Поступай на службу в полицию, спасай жизни в скорой помощи или туши пожары вместе с командой. Гоняй по набережной, отдыхай на пляже, заводи друзей или врагов. Кем станешь ты — решать только тебе. Играй прямо в браузере, ничего не скачивая.",
    "projects.lehagame.cta": "ИГРАТЬ",

    "meta.introTag": "Cinematic personal brand",
    "meta.description": "Официальный сайт Лехи Неплохо (LEHA NEPLOXO): блогер и разработчик. Сайты, программы, боты и ИИ-решения на заказ, онлайн-игра LEHA NEPLOXO WORLD и соцсети.",
    "meta.title": "Леха Неплохо (LEHA NEPLOXO) — блогер, разработчик сайтов и игр"
  },

  en: {
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.services": "SERVICES",
    "nav.projects": "PROJECTS",
    "nav.socials": "SOCIALS",
    "nav.support": "SUPPORT",
    "lang.label": "Language",

    "hero.kicker": "Personal creator",
    "hero.subtitle": "Digital projects / Content",
    "hero.cta.primary": "MY PROJECTS",
    "hero.cta.secondary": "Support the author",
    "hero.scroll": "Scroll",

    "about.label": "ABOUT",
    "about.title": "Who is LEHA NEPLOXO",
    "about.intro": "Author, content creator and the person behind the camera. I also work as a developer — building websites, programs and bots for businesses and people.",
    "about.note": "Development services ↓",
    "hero.alt": "Portrait of LEHA NEPLOXO (Leha Neploxo)",
    "about.alt": "Photo of LEHA NEPLOXO (Leha Neploxo)",

    "services.label": "SERVICES",
    "services.title": "Development on demand",
    "services.card1.title": "Websites",
    "services.card1.desc": "Landing pages and full sites — from design to launch.",
    "services.card2.title": "Programs",
    "services.card2.desc": "Automation and tools: desktop and web solutions built to spec.",
    "services.card3.title": "Bots",
    "services.card3.desc": "Telegram/Discord bots, mini-games and process automation.",
    "services.card4.title": "AI solutions",
    "services.card4.desc": "Neural network integrations, automation and AI-powered tools built to spec.",
    "services.cta": "Order a project",

    "showcase.label": "SHOWCASE",
    "showcase.title": "In motion, on camera",
    "showcase.sub": "Video as part of the story, not just a background.",
    "showcase.cta": "Watch fullscreen",

    "projects.label": "PORTFOLIO",
    "projects.title": "MY PROJECTS",
    "projects.sub": "Portfolio of finished and ongoing projects.",
    "projects.card.category": "Coming soon",
    "projects.card.date": "TBA",
    "projects.card.desc": "Project description will be added soon.",
    "projects.card.cta": "VIEW PROJECT",

    "socials.label": "FOLLOW ME",
    "socials.title": "Social media",
    "socials.sub": "Official LEHA NEPLOXO accounts.",

    "ads.label": "ADVERTISING",
    "ads.title": "Advertising & collabs",
    "ads.text": "Ad placements and integrations across TikTok, Instagram, YouTube and Facebook — tailored to each platform's format and audience.",
    "ads.cta": "Order advertising",

    "support.label": "SUPPORT",
    "support.title": "Support the project",
    "support.text": "If the content resonates, support helps create more of it.",
    "support.cta": "Support the author",
    "support.via": "via Monobank",

    "footer.tagline": "Personal creator / Digital projects / Content",
    "footer.nav": "Navigation",
    "footer.social": "Social",
    "footer.lang": "Language",
    "footer.rights": "All rights reserved.",

    "project.back": "BACK TO PROJECTS",
    "project.about": "About the project",
    "project.gallery": "Media",
    "project.links": "Links",
    "project.notfound.title": "Project not found",
    "project.notfound.text": "This project doesn't exist yet. Head back to the projects list.",
    "project.notfound.cta": "TO PROJECTS",
    "project.placeholder": "Full description, media and links for this project will be added soon.",

    "projects.cyber.title": "CYBER BIOLOGY",
    "projects.cyber.category": "Digital evolution",
    "projects.cyber.desc": "Worlds where simple bots are born, fight for energy, and evolve.",
    "projects.cyber.desc.long": "A series of artificial-evolution experiments: each world runs its own rules for birth, hunger, reproduction and mutation. Bots move, search for food and fight to survive — no script, just randomness and code.",
    "project.worlds.label": "EXPERIMENTS",
    "project.worlds.title": "Bot worlds",
    "project.worlds.sub": "Each world is its own living simulation. Open one and watch it run.",
    "project.world.enter": "ENTER WORLD",
    "project.world.number": "Bot World",
    "world.back": "BACK TO PROJECT",

    "projects.tiktokgame.title": "STREET FIGHTERS",
    "projects.tiktokgame.category": "Livestream",
    "projects.tiktokgame.date": "Live now",
    "projects.tiktokgame.desc": "An interactive game live on TikTok, where you control your character and level them up.",
    "projects.tiktokgame.desc.long": "An interactive game live on TikTok, where you control your character and level them up.",
    "projects.tiktokgame.cta": "WATCH LIVE",

    "projects.lehagame.title": "LEHA NEPLOXO WORLD",
    "projects.lehagame.category": "Online RP · Open world",
    "projects.lehagame.date": "Play online",
    "projects.lehagame.desc": "A whole city in your browser: palm trees, neon, the ocean and real players. Become a cop, a medic, a firefighter or a businessman — then decide for yourself who you want to be.",
    "projects.lehagame.desc.long": "Welcome to LEHA NEPLOXO WORLD — a sunny neon metropolis by the ocean with a fully open world. Everyone you meet on the streets is a real player. Buy apartments and houses, make money and build your fortune. Join the police, save lives as a paramedic or fight fires with your crew. Cruise the boulevard, chill on the beach, make friends or enemies. Who you become is entirely up to you. Play right in your browser — no download needed.",
    "projects.lehagame.cta": "PLAY NOW",

    "meta.introTag": "Cinematic personal brand",
    "meta.description": "Official site of LEHA NEPLOXO (Leha Neploxo, Леха Неплохо): content creator and developer. Websites, programs, bots and AI solutions on demand, the online game LEHA NEPLOXO WORLD and socials.",
    "meta.title": "LEHA NEPLOXO (Leha Neploxo) — content creator & web developer"
  }
};

/* Real projects + placeholder demo cards for future content. */
window.SITE_PROJECTS = [
  {
    id: "leha-game",
    image: "assets/img/leha-game.webp",
    video: null,
    externalUrl: "https://gameleha.xyz",
    titleKey: "projects.lehagame.title",
    categoryKey: "projects.lehagame.category",
    dateKey: "projects.lehagame.date",
    descKey: "projects.lehagame.desc",
    descLongKey: "projects.lehagame.desc.long",
    ctaKey: "projects.lehagame.cta"
  },
  {
    id: "tiktok-game-live",
    image: "assets/img/street-fighters-tiktok.jpg",
    video: null,
    externalUrl: "https://www.tiktok.com/@tiktokgame8805",
    titleKey: "projects.tiktokgame.title",
    categoryKey: "projects.tiktokgame.category",
    dateKey: "projects.tiktokgame.date",
    descKey: "projects.tiktokgame.desc",
    descLongKey: "projects.tiktokgame.desc.long",
    ctaKey: "projects.tiktokgame.cta"
  },
  {
    id: "cyber-biology",
    image: "assets/img/cyber-biology.webp",
    video: null,
    cyberVisual: false,
    titleKey: "projects.cyber.title",
    categoryKey: "projects.cyber.category",
    dateKey: null,
    descKey: "projects.cyber.desc",
    descLongKey: "projects.cyber.desc.long",
    worlds: [
      { id: "1", file: "assets/bots/world-1.html" },
      { id: "2", file: "assets/bots/world-2.html" },
      { id: "3", file: "assets/bots/world-3.html" },
      { id: "4", file: "assets/bots/world-4.html", label: "Genesis" }
    ]
  }
];
