/* ==========================================================================
   LEHA NEPLOXO — i18n dictionary + placeholder project data
   Edit this file to add real projects/texts later. Nothing here is invented
   biography/achievements — only structural placeholders per the brief.
   ========================================================================== */

window.SITE_I18N = {
  ua: {
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.services": "SERVICES",
    "nav.projects": "PROJECTS",
    "nav.socials": "SOCIALS",
    "nav.support": "SUPPORT",
    "lang.label": "Мова",

    "hero.kicker": "Personal creator",
    "hero.subtitle": "Digital projects / Content",
    "hero.cta.primary": "MY PROJECTS",
    "hero.cta.secondary": "SUPPORT THE AUTHOR",
    "hero.scroll": "Scroll",

    "about.label": "ABOUT",
    "about.title": "Хто такий LEHA NEPLOXO",
    "about.intro": "Автор, контент-мейкер і людина за кадром. Займаюся розробкою — створюю сайти, програми та боти під задачі бізнесу і людей.",
    "about.note": "Послуги розробки ↓",
    "hero.alt": "Портрет LEHA NEPLOXO",
    "about.alt": "Фото LEHA NEPLOXO для розділу About",

    "services.label": "SERVICES",
    "services.title": "Розробка на замовлення",
    "services.card1.title": "Сайти",
    "services.card1.desc": "Лендинги та сайти під ключ — від дизайну до запуску.",
    "services.card2.title": "Програми",
    "services.card2.desc": "Автоматизація та інструменти: десктоп- і веб-рішення під задачу.",
    "services.card3.title": "Боти",
    "services.card3.desc": "Telegram/Discord-боти, міні-ігри та автоматизація процесів.",
    "services.card4.title": "ШІ-рішення",
    "services.card4.desc": "Інтеграція нейромереж, автоматизація та ШІ-інструменти під ваші задачі.",
    "services.cta": "Замовити проєкт",

    "showcase.label": "SHOWCASE",
    "showcase.title": "У русі, у кадрі",
    "showcase.sub": "Відео як частина історії, а не просто фон.",
    "showcase.cta": "Дивитись у повному екрані",

    "projects.label": "PORTFOLIO",
    "projects.title": "MY PROJECTS",
    "projects.sub": "Простір для проєктів, які скоро тут з’являться.",
    "projects.card.category": "Скоро",
    "projects.card.date": "TBA",
    "projects.card.desc": "Опис проєкту буде додано найближчим часом.",
    "projects.card.cta": "VIEW PROJECT",

    "socials.label": "FOLLOW ME",
    "socials.title": "Соціальні мережі",
    "socials.sub": "Офіційні акаунти LEHA NEPLOXO.",

    "support.label": "SUPPORT",
    "support.title": "SUPPORT THE AUTHOR",
    "support.text": "Якщо контент відгукується — підтримка допомагає створювати більше. Способи підтримки з’являться тут найближчим часом.",
    "support.cta": "SUPPORT THE AUTHOR",
    "support.soon": "Скоро",
    "support.methods.patreon": "Patreon",
    "support.methods.bmc": "Buy Me a Coffee",
    "support.methods.crypto": "Криптовалюта",
    "support.methods.bank": "Банківський переказ",
    "support.toast": "Способи підтримки скоро з’являться",

    "footer.tagline": "Personal creator / Digital projects / Content",
    "footer.nav": "Навігація",
    "footer.social": "Соцмережі",
    "footer.lang": "Мова",
    "footer.rights": "Усі права захищені.",

    "project.back": "НАЗАД ДО ПРОЄКТІВ",
    "project.about": "Про проєкт",
    "project.gallery": "Матеріали",
    "project.links": "Посилання",
    "project.notfound.title": "Проєкт не знайдено",
    "project.notfound.text": "Такого проєкту ще не існує. Поверніться до списку проєктів.",
    "project.notfound.cta": "ДО ПРОЄКТІВ",
    "project.placeholder": "Повний опис, матеріали та посилання цього проєкту з’являться найближчим часом.",

    "projects.cyber.title": "CYBER BIOLOGY",
    "projects.cyber.category": "Digital evolution",
    "projects.cyber.desc": "Світи, де прості боти народжуються, борються за енергію та еволюціонують.",
    "projects.cyber.desc.long": "Серія експериментів зі штучною еволюцією: у кожному світі власні правила народження, голоду, розмноження та мутацій. Боти рухаються, шукають їжу і борються за виживання — без жодного сценарію, лише випадковість і код.",
    "project.worlds.label": "EXPERIMENTS",
    "project.worlds.title": "Світи ботів",
    "project.worlds.sub": "Кожен світ — окрема жива симуляція. Відкривайте та спостерігайте.",
    "project.world.enter": "УВІЙТИ У СВІТ",
    "project.world.number": "Світ ботів",
    "world.back": "НАЗАД ДО ПРОЄКТУ",

    "projects.tiktokgame.title": "STREET FIGHTERS",
    "projects.tiktokgame.category": "Прямий ефір",
    "projects.tiktokgame.date": "Наразі в ефірі",
    "projects.tiktokgame.desc": "Інтерактивна гра в прямому ефірі TikTok, де ти керуєш своїм персонажем і прокачуєш його рівень.",
    "projects.tiktokgame.desc.long": "Інтерактивна гра в прямому ефірі TikTok, де ти керуєш своїм персонажем і прокачуєш його рівень.",
    "projects.tiktokgame.cta": "ДИВИТИСЬ ЕФІР",

    "meta.introTag": "Cinematic personal brand"
  },

  ru: {
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.services": "SERVICES",
    "nav.projects": "PROJECTS",
    "nav.socials": "SOCIALS",
    "nav.support": "SUPPORT",
    "lang.label": "Язык",

    "hero.kicker": "Personal creator",
    "hero.subtitle": "Digital projects / Content",
    "hero.cta.primary": "MY PROJECTS",
    "hero.cta.secondary": "SUPPORT THE AUTHOR",
    "hero.scroll": "Scroll",

    "about.label": "ABOUT",
    "about.title": "Кто такой LEHA NEPLOXO",
    "about.intro": "Автор, контент-мейкер и человек за кадром. Занимаюсь разработкой — создаю сайты, программы и ботов под задачи бизнеса и людей.",
    "about.note": "Услуги разработки ↓",
    "hero.alt": "Портрет LEHA NEPLOXO",
    "about.alt": "Фото LEHA NEPLOXO для раздела About",

    "services.label": "SERVICES",
    "services.title": "Разработка на заказ",
    "services.card1.title": "Сайты",
    "services.card1.desc": "Лендинги и сайты под ключ — от дизайна до запуска.",
    "services.card2.title": "Программы",
    "services.card2.desc": "Автоматизация и инструменты: десктоп- и веб-решения под задачу.",
    "services.card3.title": "Боты",
    "services.card3.desc": "Telegram/Discord-боты, мини-игры и автоматизация процессов.",
    "services.card4.title": "ИИ-решения",
    "services.card4.desc": "Интеграция нейросетей, автоматизация и ИИ-инструменты под ваши задачи.",
    "services.cta": "Заказать проект",

    "showcase.label": "SHOWCASE",
    "showcase.title": "В движении, в кадре",
    "showcase.sub": "Видео как часть истории, а не просто фон.",
    "showcase.cta": "Смотреть в полном экране",

    "projects.label": "PORTFOLIO",
    "projects.title": "MY PROJECTS",
    "projects.sub": "Пространство для проектов, которые скоро здесь появятся.",
    "projects.card.category": "Скоро",
    "projects.card.date": "TBA",
    "projects.card.desc": "Описание проекта будет добавлено в ближайшее время.",
    "projects.card.cta": "VIEW PROJECT",

    "socials.label": "FOLLOW ME",
    "socials.title": "Социальные сети",
    "socials.sub": "Официальные аккаунты LEHA NEPLOXO.",

    "support.label": "SUPPORT",
    "support.title": "SUPPORT THE AUTHOR",
    "support.text": "Если контент откликается — поддержка помогает создавать больше. Способы поддержки появятся здесь в ближайшее время.",
    "support.cta": "SUPPORT THE AUTHOR",
    "support.soon": "Скоро",
    "support.methods.patreon": "Patreon",
    "support.methods.bmc": "Buy Me a Coffee",
    "support.methods.crypto": "Криптовалюта",
    "support.methods.bank": "Банковский перевод",
    "support.toast": "Способы поддержки скоро появятся",

    "footer.tagline": "Personal creator / Digital projects / Content",
    "footer.nav": "Навигация",
    "footer.social": "Соцсети",
    "footer.lang": "Язык",
    "footer.rights": "Все права защищены.",

    "project.back": "НАЗАД К ПРОЕКТАМ",
    "project.about": "О проекте",
    "project.gallery": "Материалы",
    "project.links": "Ссылки",
    "project.notfound.title": "Проект не найден",
    "project.notfound.text": "Такого проекта пока не существует. Вернитесь к списку проектов.",
    "project.notfound.cta": "К ПРОЕКТАМ",
    "project.placeholder": "Полное описание, материалы и ссылки этого проекта появятся в ближайшее время.",

    "projects.cyber.title": "CYBER BIOLOGY",
    "projects.cyber.category": "Digital evolution",
    "projects.cyber.desc": "Миры, где простые боты рождаются, борются за энергию и эволюционируют.",
    "projects.cyber.desc.long": "Серия экспериментов с искусственной эволюцией: в каждом мире свои правила рождения, голода, размножения и мутаций. Боты двигаются, ищут еду и борются за выживание — без сценария, только случайность и код.",
    "project.worlds.label": "EXPERIMENTS",
    "project.worlds.title": "Миры ботов",
    "project.worlds.sub": "Каждый мир — отдельная живая симуляция. Открывайте и наблюдайте.",
    "project.world.enter": "ВОЙТИ В МИР",
    "project.world.number": "Мир ботов",
    "world.back": "НАЗАД К ПРОЕКТУ",

    "projects.tiktokgame.title": "STREET FIGHTERS",
    "projects.tiktokgame.category": "Прямой эфир",
    "projects.tiktokgame.date": "Сейчас в эфире",
    "projects.tiktokgame.desc": "Интерактивная игра в прямом эфире TikTok, где ты управляешь своим персонажем и прокачиваешь его уровень.",
    "projects.tiktokgame.desc.long": "Интерактивная игра в прямом эфире TikTok, где ты управляешь своим персонажем и прокачиваешь его уровень.",
    "projects.tiktokgame.cta": "СМОТРЕТЬ ЭФИР",

    "meta.introTag": "Cinematic personal brand"
  },

  en: {
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.services": "SERVICES",
    "nav.projects": "PROJECTS",
    "nav.socials": "SOCIALS",
    "nav.support": "SUPPORT",
    "lang.label": "Language",

    "hero.kicker": "Personal creator",
    "hero.subtitle": "Digital projects / Content",
    "hero.cta.primary": "MY PROJECTS",
    "hero.cta.secondary": "SUPPORT THE AUTHOR",
    "hero.scroll": "Scroll",

    "about.label": "ABOUT",
    "about.title": "Who is LEHA NEPLOXO",
    "about.intro": "Author, content creator and the person behind the camera. I also work as a developer — building websites, programs and bots for businesses and people.",
    "about.note": "Development services ↓",
    "hero.alt": "Portrait of LEHA NEPLOXO",
    "about.alt": "Photo of LEHA NEPLOXO for the About section",

    "services.label": "SERVICES",
    "services.title": "Development on demand",
    "services.card1.title": "Websites",
    "services.card1.desc": "Landing pages and full sites — from design to launch.",
    "services.card2.title": "Programs",
    "services.card2.desc": "Automation and tools: desktop and web solutions built to spec.",
    "services.card3.title": "Bots",
    "services.card3.desc": "Telegram/Discord bots, mini-games and process automation.",
    "services.card4.title": "AI solutions",
    "services.card4.desc": "Neural network integrations, automation and AI-powered tools built to spec.",
    "services.cta": "Order a project",

    "showcase.label": "SHOWCASE",
    "showcase.title": "In motion, on camera",
    "showcase.sub": "Video as part of the story, not just a background.",
    "showcase.cta": "Watch fullscreen",

    "projects.label": "PORTFOLIO",
    "projects.title": "MY PROJECTS",
    "projects.sub": "Space for projects that will appear here soon.",
    "projects.card.category": "Coming soon",
    "projects.card.date": "TBA",
    "projects.card.desc": "Project description will be added soon.",
    "projects.card.cta": "VIEW PROJECT",

    "socials.label": "FOLLOW ME",
    "socials.title": "Social media",
    "socials.sub": "Official LEHA NEPLOXO accounts.",

    "support.label": "SUPPORT",
    "support.title": "SUPPORT THE AUTHOR",
    "support.text": "If the content resonates, support helps create more of it. Ways to support will appear here soon.",
    "support.cta": "SUPPORT THE AUTHOR",
    "support.soon": "Soon",
    "support.methods.patreon": "Patreon",
    "support.methods.bmc": "Buy Me a Coffee",
    "support.methods.crypto": "Crypto",
    "support.methods.bank": "Bank transfer",
    "support.toast": "Support options are coming soon",

    "footer.tagline": "Personal creator / Digital projects / Content",
    "footer.nav": "Navigation",
    "footer.social": "Social",
    "footer.lang": "Language",
    "footer.rights": "All rights reserved.",

    "project.back": "BACK TO PROJECTS",
    "project.about": "About the project",
    "project.gallery": "Media",
    "project.links": "Links",
    "project.notfound.title": "Project not found",
    "project.notfound.text": "This project doesn't exist yet. Head back to the projects list.",
    "project.notfound.cta": "TO PROJECTS",
    "project.placeholder": "Full description, media and links for this project will be added soon.",

    "projects.cyber.title": "CYBER BIOLOGY",
    "projects.cyber.category": "Digital evolution",
    "projects.cyber.desc": "Worlds where simple bots are born, fight for energy, and evolve.",
    "projects.cyber.desc.long": "A series of artificial-evolution experiments: each world runs its own rules for birth, hunger, reproduction and mutation. Bots move, search for food and fight to survive — no script, just randomness and code.",
    "project.worlds.label": "EXPERIMENTS",
    "project.worlds.title": "Bot worlds",
    "project.worlds.sub": "Each world is its own living simulation. Open one and watch it run.",
    "project.world.enter": "ENTER WORLD",
    "project.world.number": "Bot World",
    "world.back": "BACK TO PROJECT",

    "projects.tiktokgame.title": "STREET FIGHTERS",
    "projects.tiktokgame.category": "Livestream",
    "projects.tiktokgame.date": "Live now",
    "projects.tiktokgame.desc": "An interactive game live on TikTok, where you control your character and level them up.",
    "projects.tiktokgame.desc.long": "An interactive game live on TikTok, where you control your character and level them up.",
    "projects.tiktokgame.cta": "WATCH LIVE",

    "meta.introTag": "Cinematic personal brand"
  }
};

/* Real projects + placeholder demo cards for future content. */
window.SITE_PROJECTS = [
  {
    id: "cyber-biology",
    image: "assets/img/cyber-biology.png",
    video: null,
    cyberVisual: false,
    titleKey: "projects.cyber.title",
    categoryKey: "projects.cyber.category",
    dateKey: null,
    descKey: "projects.cyber.desc",
    descLongKey: "projects.cyber.desc.long",
    worlds: [
      { id: "1", file: "assets/bots/world-1.html" },
      { id: "2", file: "assets/bots/world-2.html" },
      { id: "3", file: "assets/bots/world-3.html" },
      { id: "4", file: "assets/bots/world-4.html", label: "Genesis" }
    ]
  },
  {
    id: "tiktok-game-live",
    image: "assets/img/street-fighters-tiktok.jpg",
    video: null,
    externalUrl: "https://www.tiktok.com/@tiktokgame8805",
    titleKey: "projects.tiktokgame.title",
    categoryKey: "projects.tiktokgame.category",
    dateKey: "projects.tiktokgame.date",
    descKey: "projects.tiktokgame.desc",
    descLongKey: "projects.tiktokgame.desc.long",
    ctaKey: "projects.tiktokgame.cta"
  }
];
